prediction_objective:
  operator: OR
  events:
  - Battery_Active_Power_0_20-to-80_100
  - Battery_Active_Power_20_60-to-80_100
  - Battery_Active_Power_60_80-to-80_100
parent_variant: v111
prediction_name: molamas
